name: Cypress Tests demo

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug
        run: pwd
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: '14.x'
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - run: |
          npm install --save-dev
          npm install cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
