name: Run e2e test by manual


on:
  workflow_dispatch:
    inputs:
      select_project:
        description: 'select project'
        required: true
        default: 'automationExercise'
        type: choice
        options:
            - saucedemo
            - automationExercise
      select_environment:
        description: 'select test environment'
        required: true
        default: qa
        type: choice
        options:
            - qa
            - staging
            - production
            

jobs:
    run-e2e-test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Checking out the code for ${{github.event.inputs.select_project}}"
            - run: echo " Running on e2e test environment ${{github.event.inputs.select_environment}}"
