name: Run e2e test by manual


on:
  workflow_dispatch:
    inputs:
      select_project:
        description: 'select project'
        required: true
        default: 'automationExercise'
        type: choice
        options:
            - saucedemo
      select_environment:
        description: 'select test environment'
        required: true
        default: qa
        type: choice
        options:
            - qa
            - staging
            - production
            

jobs:
  prepare-test:
    runs-on: ubuntu-latest
    steps:
        - run: |

        - run: echo "Checking out the code for ${{github.event.inputs.select_project}}"
        - run: echo " Running on e2e test environment ${{github.event.inputs.select_environment}}"
        - name: checkout code
          uses: actions/checkout@v2

        - name: Set Environment URL
          env:
            QA_URL: ${{ secrets.QA }}
            STAGING_URL: ${{ secrets.STAGING }}
            SELECTED_ENV: ${{ github.event.inputs.select_environment }}
          run: |
            if [ $SELECTED_ENV == "QA"]; then
              echo $ENV_URL=$QA_URL >> $GITHUB_ENV
            elif [ $SELECTED_ENV == "STAGING" ]; then
              echo $ENV_URL=$STAGING_URL >> $GITHUB_ENV
            else
              echo "No environment selected"
            fi
            
        - name: Set up Node.js
          uses: actions/setup-node@v4.0.2
          with: 
            node-version: '14.x'
            cache: "npm"
            cache-dependency-path: "package-lock.json"
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            start: npm run start
            test: npm run test:saucedemo
 
